apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCjrpK6PtbmMqIsZ3CS9T8Cme3Mb7mC4GOqZC4QTXObfdguqF/MAuUqMRw+CVtN0ioT0j4WJViI77036sIirDA3QQy5sNudGUwqaqY7fJpeOxCd7oRuh9jpZXA6tF9Xswd1qwinZJ4nrvigEXTerk5E2H7JFV69p0fBG7wC1vxSwvmb8ro5K28wvGJnnWst7yWHNXH5s5lWviSkGsoo7LRd7HF5ZafmTlFo8t4gDNHQfatGyIkCZJh6755+RnfeDbfyhYyGAmigE72yOuqBinskuyyCidd0Hz1A6ZPT4nlqhkHIk44onybMwDL2bMOVjQ5ciWmRt8Ayi38cBAEQuTLAOvnYxDMJQGzw+XUkdxokJ/dZEYg2xRVouthQE53+d4SmUJbxs/IXqgC8pK5UUCC8UiIci9N0vMO/xDoXzRLxku9AvjjPD8cRxG1muyWSsjJG2kqvwm6N8q5L+3jxuePPUSOYWtuY2Zzip8gPPDDKooWhZdTULzY3vARCw8cJdBI3+GOw3MMP5ailG7T4ZFYPYlPEXITPTT8KTwiCndcXwWRsu1pDEap+MTsSl/Bx9whsY755r2mx3WImpKcI15eXthVIgLJmSBOH9L1CmktjT273eYewrBU38qqbQHIEGDL/kI5IBPFxIGMkSK7snQ3Mv0A5yFQdQHuG1FLjwt8+s1tm55jl3Uwlgjulifz43WKyL7FACyVGwRTqdgtJxVQjY7toAPusf7zaKz7RmdBgx6OVR4EmJjcQ5vm819auOeB5yAtbdxCL6EmUqOBHPNowXpU8KcvXkDOfdLwj/56Y+sbNu9GORmDtqdiW8ovVnbLQNfKCthaA/angJ0GUZ6rAz5slsG1ruj5uPf7HL65L4z5RKGGj/GM080BUGYt++SUEFPtkI2di/lev+Uo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

