apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCdiJI/SnUbimrtAzG51EztEHUIf7RSpaV2WYv7+jMIJ8gOrAKvrHgHAidBAeGe93AVucthMq+vIl5Ee5Jentz6U84Co/RnHptYDXfaZAEmUHuVEMIWXUW6Bf9EHBUGWdSbYtbQSpPrZOWHEeVttZWxgGyKX+eb2WA146j3Vi3Tm2+hspr89CeiS2pmAbi7Md6aGJr2lcZwIyHVg/8AoY5amDJAZBGUzlFr0AdhNA+CgKXdxelGn3FeQmNdmhu7FGx5wJEirz55gd+A+qK10VTWDsOti1eOZ4so8LEajYJGC4iVkPbfLmcgHUG+PBeoivnTvdGnsGCkjPl+zuCO5a99dGE4h7QmA2bMbzjFE6Z7aEY/yYIvE/XlAVn+VcIQSaLXAEO1s4hrATgSdHEYba3td8mcSbMAFPPh6Ce0PfmF3DnjCzO3uyxu9i7lAlYbsPtUnrQT2CjPWxMkScOGnEsKdMiBL6NdC9Wskyk8iWehjYRmtNGpNW0ADvNVHoOGMiMr9ZH0VjqnPY3euHfylCXoQIPjZDhF7UM9U+UTjtJV6/LIMuyALP97fpEMMzkzYHM5toLBSKrYtOYjeO/tnSwEmcXo8gNDkXC5l5nTzGzhixdOeBY/eU8/DrJGMHnpb5iosr9bnFxJSwg6/K3lOsY1wtOlW98KBvC35V7q3OJeRdoBSn7EYGYbYzDyLy0LNp4WkGKfLfwtEVYS4qqMt4jbFQ5LT9a9MfV4da9rizNwK2wglIe9WmK1IlJGsAVfSyg/r/r2FLhOvgZqx26uZCzqbEyTo4FTSdlMJkeYir7BPM0vibnpclLyW8makGUBOdxLzS/8dPqCZi3EufPw2OEjC6qIo7/Mz+EseDjtEujfT1Bgfurg9c/CQC7qY3S2aowg8M/E67wtEvBQe8U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

