apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAKnn+zQFyiCG7vGGmEn3bIbYTfj6asUnYLPNeq5iEJ4TqICpCzhyzSroszia8Ab9CvDOTVBi6xxXCoG4GfTNbcWybnlvkaDfNskQtCEs2nZVtxTJmxqI9WYrksJz99btErHTdx2z8ePPGF0A5KJadS3slJF4DTuf4k07v4VGIwrDCWkFmNl2/iqGRZshphgJOZAaNtl715uyCzzK7g0UQY/yx0RhwQBWnoZpi9hz5FTcDeZyYTXErc/XoSDAJ5Ge28yh/oK6z/nGDq/3E4L9Bgg7jxraBk0ZCGsuqus0uJ94rpScNxB+iQj0tWT4/INeTS9vdmPhfxNUd3unCBVR9WlcP+JMxvRW/38wP91RhsAcAEELl3uwYv7pAb96N71cvDus41EKYlRHGMx6ovjaW+uQ7Ww0r8gM1n4C077OVishe6QbTTHih+FojhlngqtzVPpQAfIAzIGZjjmtYlmQ0Xjx61C8qbybtL7wyc1hnC5vehb1GD5Xbdzc1FJKfEK1YCnwva+Lk7264iZCzktNQ8ISupFnKaoB0bzQqocAFGz0L089HFOgje+w80ivYjbTmEV7yVTf3psnp1mTxzmx+UYAknbJ+kJyFgdlUwAB82Qxbi+QCs0lnjYSgea08Hf02EAwdcrlBlsjbw/7EDo4GT1kSCkU2Pu5FpRwk3/TFJA2QD/yaXgR8jHkqG2n773WOC25R6Yhg43Ca/3X+jVSqDlO32Wu8Kk/fYuW973X0iFx/59cIij+MRk8GR2vj32ItfSOrC6CwGJRcunlMquRrfgVISEMsaT0ftY27sbhC/203CXlH0YSJc4tYABCEbLkXmeFXddA25STXtznw1K5MHE/8hBOFCn53PgG7Vu8qRX+/xxRjBfGi874Lz9RB5sZyqbBHQpqqBvP3KGDg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

