apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBewwvmJh5n0/FHexfE3E1q3tq5syTO+SE9AlIPxD854+gMjga7Jf3ubZcUJ6vCjG2D4peUBwExbOYT2snGLtMgXEkvDRj8NXQFmeM/WDo/mNlJNFFgYd49mmYvG2a0S9ahVvIYu3ydoZoDYT2mbUerDvsQteehafrRloX10WApFuea+w53hORrfUasckuvU2xUj9VEuCTXJQOjtIZyZW5YjpbHaBjYwPOlkeavYtViKJp5HF6YsCqGT//RPn7rCSBnuo+nc45zPrnyTtRqo4RVVNgwjkvmWafDd7tnVBeCRyeovdPWpOvX3JkYEhJSyaXcf/WDn1LzyIgt7EzKKLS9T2CK+1zuFo/1XZgfkhNDIsOxNk+Ugw0FINOXbDFdFRRfNDqUpw63C6Xjh9MJtjMpIyrt6Rs76IHTDmQXUehIyv28dQX+2jCiqc0ipxD1WSF3IMznv/oBQlKRy7KWMsh5nhmSs8/byLhbMe5o9eh1XW0Imm17tn+lOZJYhj09RVmaXrhmdgHprqf/hYIy7ZmPCEc1jvXX7XiTGUYdFqdtV7yZgc8LVAtlL1Fmubdd30jzxcqgHsYDZEQ8Z7VXbNqHYBMcZxxME0Zfl4ph7ixziA2r2tiq6gK3SwDb3j1zZz9B1V0/APY1XSkX5LWfOUXKQVSDVdhkcszh7vlxGrq958hotfLd7WRrPRaDYWV4Hyhvo8KZofZFCu8rRIvcFsLUBtlVDeZCP8hGiZg9i9YsHSIynZ4hS/r/UtrXD6+dqxb6lltWxiCCWsxaus6n789+RUZ6fqy7WLqXJo9Q/qUlzwZQ12Yt1s7gjTKkeFLLWjqnGBsk0zUQiL1tRHqtIaGDJlPOFRmde211Q+FJ/PKqH2E+UUhj7ojWMuxYwYpgPlA+Lv5d6RTWAierfPI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

