apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoevents
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: charts/argo-events
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: HEAD
    helm:
      values: |
        server: 
          ingress:
            - hosts:
              - webhook.212.2.245.35.nip.io
            enabled: true
            ingressClassName: nginx
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

