apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCzIBvj2rlM3SrwDdG1TPlFH51YsqB43rFqVC9uAOLISUwBq8EoetR9BnwL+E/bIftaq2+3EUjUEui5p4WJRyH9wFq/DLbeHmhkr3sp+gqpny7zwvQDb8z7a7q2xsrdBp7/940bOZdWTnYz2aXYjo/5YfwaGi93N9hO3w+xxaTYMwsaKL3CEuVqwDtXpr23c01ee4XOmSykE3PrJsWIprFcZ/fAQrGqrMqNhtFGq0pqUSvD2JPfLyBe20XH4yeTO3unUSchnVHk8x3UnzMpJyE6Zma28xWnUWMDvSa0gacQoAtF9rN8330MH8FSbc7PKLV6k/A9YGWFdBXZOMuOdvJq1j9+zaYEvneipdCsOCekTBBCQ3RYf/XjE4z8vIT2bu8TkXamFa1OC0k1/ThK2u5Pp9Gz/Ly7unSNWI8rUXvCJvKmB4dHrcnFiAsHwg4ZKGQgsMP6U1Sa0nZ18A0QLoAx85cDFm4I290ihNwKmtPMyyd5UHQKhF4ZtCF4Csf3Pt1ZIPNMSOSLkpkWraxAJBzR85aMy9Gm/0D4P5afxpqRrYHTG9P5r3tMjs4/FR2+TeFk/fKel6EkRn0T3lR9H3160cs3bTTsCfQwt7ZjQeLBQsQ9ofGF9B/1uniPbsnPbgm3ewSgMjhKmiVGqlIN3XuIeBnAB7Oift9tzCPBfhGVp5gBWEVIaO5B3KOGEtoU4VQB5hUjcuDDlarBGGhfGUEoZ8XLgYnfHz36PKj5uvxCLXL2ZghI7Ady
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

