apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAdX0Z/2fAZWoZ8GxT26vhWGqAETF6RkopAASctdkJCM91vwh2q+DbwPBH5rGPSGJ0Tms5fk/d/L8JwCEOFYSrf1tEvtypneUQNV8jYz5UPlJVGVz9xDlKXXXyiCa3fJth8ZFo0yGtftWBZM7g+ONYKBzRhuHQd7hiJqb5VMbu4XgDIZ2qz0BEV3Hlhzjc/nYOks3kgoYE7wxBkoHLbdvbqhQJHWUgkaoe+s4NqZPR9Ds1bFLaUWheXcKNILShF85eqXNZFrIvh5krwjTIBQwgzZ5/PSkXgUqDYftwFIS35tTzXz7nhif7f1yB2cTPbGSbVkP2ALci+MAoegp9+NqHSfP89kHrJwuUAqca0/qALMphv0YYid+iRrZk0Cx4qZ0O8NLtiPqmgWq9UpTG8as8pgOisNk8kBqu0hAVt9ii9txFbPLC0JKJdjDEBJM5YYJrXHUXQ+xuHwamXw76JI0BO57s/GFBSAAdzhpUv8G4iF8G6TajpllFM6IKyoYbr2k5DQ4JCQ6uU1FrvqOH1A7EGc0GANr27ulUvE4w6EbXsWkplVzP8Ro7I+Ttktsl/FOrve3v03KqbCX5O0hpbIycraqXpcfTYXku9XcIcpAiPC6ILq4tfjfnWCgydCMAEklBpLti853tszsCBjXeBU0ZaCOie7ALZC/KHHFu00/XjO8+pGUyBQ+DbTVn02bVvQdaVFbXOPgp010rrtjFUuEYJe/PWwJ7Mij4QA3VnqSWLo5RzP1fak/sl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

