apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCi9eS2tzAHJVpLxfopaNTIfD1u4lTEeWt93Rnz09rAORmgo+M3Bz3FhGB0+M0sYVefE9cnyLtvOE7CibngpppRJ/vblFEMHnFAgSBXw+ccvtl6OaKKlMio6fjm2ulFZ23JGywkBzeM9zavNfHUIuTIqokKdnI0rwlZTPUlHxKYVQvIoXtppnlwOzDj3whGSG6Z3F0baZZw3NP7IQu4SmUL90X2jE7vY7IJ3MsY0UpS1+Vglw22LFL8ugedGfBpSJnoAhsPzj05JZ1yPcpQIFb74/ICzcTWMTG4TKCO3vuU+s3FHVR5n9rxYBrqj4Ep4VXoH2g4cHugtRlLYdOMokMmHBjsJ/6isnWNj/vtF0/9313U5mgEB39fM6ojxdUDw+uo0W9nOQygMI51YKApRo1I1OCq/cpQn5XeiuaG4qKohi9jNeBIWVu0l3kU3zGku8anDYtjpuB1ZLte2/DvToD6D115zpoPjM1/ynoMOChqTpZGHo0s9z5uW2+hzMUqQor4YoKNi7ZRztEJH/39+zN78ZPKiOX4Qxmmlj9inTfhtdWHs3uXc8VGeQnYmdz96nXgDKhtxx6ddp1F7fkzoeNGYkHEfb/b9F51eOBmj+C7CJNER4q3X8rARjrzC8F3YNB157jH+dze/k2ZkVa9NWyksX03Er6wIHkSDx+0SZqZv9ptD4Wr7X5hKHE9/m0WQc1ZqU3ozj8EnjzQs/GeGAp7ieCbxr1kSfkaFEzQHjhjGvXHgNj4XZeU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

