apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCQD7gMkwAAXKvOYBVGeUkbG5uKFMtPF35OwZHBcR5em8WdSAQbgQdO99mzM4qrrjEU05E2zo53tDdCpf91jyOj680tVh64343YXBlSev+wtVEnBWMcWdVwv5Yp1vYnPKf/neojD8QTgqmoBFho7e6sbkGBPO4tKsRn8MsjFX/3VOLW1R4ew0eVblcIbO4XTgFxUOXM6u7b+y0hGXbJGnjIrILkwzjYe0YO6IvtMiu8ko0U3ctmX+GE7318fTkCwWbntMkcvbBQCpvxNFIldpwaOfMnLkvqK0tFAnfKH2BNfg8v1V1cnF6fqqiE8q3/rUCwPfid2t0CzWLjsnH3OFN8nNSh/NaikJW8jwXuCFIG6VvPE8qdTpOHm4JD57FJlbbDTD2rOhfPMN7vS2gMnB+0x9zqwzCGmjcliGH6jCe/WpYbC0g6pyMWPyQMezvNJU/yy4LYQUmtkBBGnKdtV9YE0cIloLqxkGLLQQ/vEQYEas0MErPsUlnUu88eoxGJZPjVeGAU/65KE1ETjiWzUFEaDdt/S/LS1fIXQRR6Z5z4L0bDrBN9+g97YyfZyj8NDcMIGvurs9Z6e1h01N1V2hYUlb2+lE/yRT9IPDNCrEy5SAfzLux7pigx+yNyHfdcewBoLvva46hpBo9UJSEcYJLO1QZDZwfMAKGBouYo0iUbBVAV1ggV/6Urgck0FIcgkYz6f161zCrycDwFaCOVtdMaChXUsrV0VbA3QPMmmY8Izph58AnZTAVY
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

